theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
#include:
#  - index.md
#  - 2016/index.md
title: Owen Kaluza
description: Senior Research Software Engineer (Visualisation) at ACCESS-NRI
logo: https://avatars.githubusercontent.com/u/6336397?v=4
