theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
#include:
#  - index.md
#  - 2016/index.md
title: Owen Kaluza
description: Visualisation Software Specialist at Monash eResearch Centre
logo: https://avatars.githubusercontent.com/u/6336397?v=4
